### ISSUE TITLE
Type of property $loader

### ISSUE THREAD

**Issue by Lumeriol** [vodickavaclav/nette-encore#2]
There is a new error with prepared Nette\DI 4.x

Type of property vavo\EncoreLoader\EncoreLoaderTrait::$loader is not declared.

In trait on line 7 should be public EncoreLoaderFactory $loader;
With minimum version of PHP 7.4 it should not be problem with backward compatibility.

**Comment by vodickavaclav** [comment]
Thank you for your comment. 
The new nette/di requires PHP >=8.0.  I will take look at it when the new version will be released.

**Comment by vodickavaclav** [comment]
Type of EncoreLoaderTrait::$loader property has been added in version 1.2.4
